# Model 
pretrained_folder: /srv/homes/onbo10/thesis_main/weights/original_weights/S2M2
model_type: S
num_refine: 3
allow_negative: False
# Data 
left_img_root: data/SurgPose/SurgPose_for_HRNet/Extracted/extracted_frames  
right_img_root: data/SurgPose/SurgPose_for_HRNet/Extracted_right_test/extracted_frames 
zip_root :  data/SurgPose/SurgPose_for_HRNet
split_file: data/SurgPose/SurgPose_for_HRNet/Extracted/video_split.yaml
split_value: test
h: 986
w: 1400
save_visuals : False
lrc_threshold: 1 
resized: True
# Output folder 
output: results/Stereo_matching/Surgpose_test_disparity_maps/s2m2





